version: '3'

services:
  backend:
    build:
      context: ./CrespoAppProject
    volumes:
      - ./CrespoAppProject:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - backend