version: '3'

services:
  backend:
    build:
      context: ./CrespoAppProject
    env_file:
      - ./CrespoAppProject/.env
    volumes:
      - ./CrespoAppProject:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./ui
    env_file:
      - ./ui/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend